name: executor-service
hostname: grading

replicaCount: 1

image:
  repository: vucongtuanduong/grading-executor
  tag: "v1.0.17"
  pullPolicy: Always

global:
  domain: vucongtuanduong.dpdns.org
  prefix: dev2

spring:
  profilesActive: stg

service:
  type: ClusterIP
  port: 8083

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi
